instrumentation:
  root: .
  extensions:
    - .js
    - .ts
  default-excludes: true
  excludes:
    - "**/*.no-cover.js"
    - "**/__tests__/**" #no need to instrument this test code! Things references by it remain covered.
    - "**/internal/errors.*" #contains things like exception throws, not executable code
    - "**/lib/index.ts" #no executable code
